"use server";
import { revalidatePath } from "next/cache";
import { createAdminClient, createClient } from "@/lib/supabase/server";

async function requireAdmin(){const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user) throw new Error("Not authenticated");const {data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(!profile||!['admin','super_admin'].includes(profile.role)) throw new Error("Not authorized");return user;}

export async function uploadAcademicDocument(formData:FormData){const user=await requireAdmin();const type=String(formData.get("document_type")??"") as "academic_calendar"|"final_exam_schedule";const termRaw=String(formData.get("term")??"").toLowerCase();const term=(["spring","summer","fall"] as const).includes(termRaw as "spring"|"summer"|"fall") ? termRaw as "spring"|"summer"|"fall" : null;const year=Number(formData.get("year"));const title=String(formData.get("title")??"").trim();const file=formData.get("file");if(!['academic_calendar','final_exam_schedule'].includes(type)||!term||!year||!title||!(file instanceof File)||file.size===0) throw new Error("Please complete all document fields.");if(file.type!=="application/pdf" && !file.name.toLowerCase().endsWith(".pdf")) throw new Error("Only PDF files are allowed.");if(file.size>30*1024*1024) throw new Error("PDF must be 30MB or smaller.");const admin=createAdminClient();const {data:oldDoc}=await admin.from("academic_documents").select("storage_path").eq("document_type",type).eq("term",term).eq("year",year).maybeSingle();const path=`${type}/${term}-${year}-${Date.now()}.pdf`;const bytes=new Uint8Array(await file.arrayBuffer());const {error:uploadError}=await admin.storage.from("admin-documents").upload(path,bytes,{contentType:"application/pdf",upsert:false});if(uploadError) throw new Error(uploadError.message);const {error:dbError}=await admin.from("academic_documents").upsert({document_type:type,term:term as any,year,title,storage_path:path,file_size_bytes:file.size,uploaded_by:user.id,is_active:true},{onConflict:"document_type,term,year"});if(dbError){await admin.storage.from("admin-documents").remove([path]);throw new Error(dbError.message);}if(oldDoc?.storage_path&&oldDoc.storage_path!==path) await admin.storage.from("admin-documents").remove([oldDoc.storage_path]);revalidatePath("/admin/academic-tools");revalidatePath("/tools/academic-calendar");revalidatePath("/tools/final-exams");}

export async function createDeadline(formData:FormData){const user=await requireAdmin();const admin=createAdminClient();const title=String(formData.get("title")??"").trim();const description=String(formData.get("description")??"").trim();const category=String(formData.get("category")??"Academic").trim();const term=String(formData.get("term")??"").trim().toLowerCase()||null;const yearRaw=String(formData.get("year")??"").trim();const dueAt=String(formData.get("due_at")??"").trim();const link=String(formData.get("link")??"").trim();if(title.length<3||!dueAt) throw new Error("Title and due date are required.");const {error}=await admin.from("deadlines").insert({title,description:description||null,category,term:term as any,year:yearRaw?Number(yearRaw):null,due_at:new Date(dueAt).toISOString(),link:link||null,is_active:true,created_by:user.id});if(error) throw new Error(error.message);revalidatePath("/admin/academic-tools");revalidatePath("/tools/deadlines");}

export async function deleteDeadline(formData:FormData){await requireAdmin();const admin=createAdminClient();const id=String(formData.get("id")??"");await admin.from("deadlines").delete().eq("id",id);revalidatePath("/admin/academic-tools");revalidatePath("/tools/deadlines");}


export async function createAnnouncement(formData:FormData){const user=await requireAdmin();const admin=createAdminClient();const title=String(formData.get("title")??"").trim();const body=String(formData.get("body")??"").trim();const badge=String(formData.get("badge")??"").trim();const ctaLabel=String(formData.get("cta_label")??"").trim();const ctaLink=String(formData.get("cta_link")??"").trim();const starts=String(formData.get("starts_at")??"").trim();const ends=String(formData.get("ends_at")??"").trim();const priority=Number(formData.get("priority")??0);if(title.length<3||body.length<3) throw new Error("Title and message are required.");const {error}=await admin.from("announcements").insert({title,body,badge:badge||null,cta_label:ctaLabel||null,cta_link:ctaLink||null,starts_at:starts?new Date(starts).toISOString():null,ends_at:ends?new Date(ends).toISOString():null,is_active:true,priority,created_by:user.id});if(error) throw new Error(error.message);revalidatePath("/admin/academic-tools");revalidatePath("/");}

export async function toggleAnnouncement(formData:FormData){await requireAdmin();const admin=createAdminClient();const id=String(formData.get("id"));const active=String(formData.get("active"))!=="true";await admin.from("announcements").update({is_active:active}).eq("id",id);revalidatePath("/admin/academic-tools");revalidatePath("/");}

export async function updateRequestStatus(formData:FormData){await requireAdmin();const admin=createAdminClient();const id=String(formData.get("id"));const status=String(formData.get("status"));const note=String(formData.get("admin_note")??"").trim();if(!['open','in_progress','fulfilled','closed'].includes(status)) throw new Error("Invalid status");const {data:req}=await admin.from("resource_requests").select("user_id,title").eq("id",id).single();const {error}=await admin.from("resource_requests").update({status:status as any,admin_note:note||null}).eq("id",id);if(error) throw new Error(error.message);if(req){await admin.from("notifications").insert({profile_id:req.user_id,type:"resource_request_update",title:"Resource request updated",body:`${req.title} is now ${status.replace("_"," ")}.`,link:"/tools/resource-request"});}revalidatePath("/admin/academic-tools");revalidatePath("/tools/resource-request");}
