"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { createAdminClient, createClient } from "@/lib/supabase/server";

type BannerStatus = "draft" | "published" | "scheduled" | "hidden";

async function requireAdmin(){const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user) throw new Error("Not authenticated");const {data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(!profile||!['admin','super_admin'].includes(profile.role)) throw new Error("Not authorized");return user;}

export async function uploadAcademicDocument(formData:FormData){const user=await requireAdmin();const type=String(formData.get("document_type")??"") as "academic_calendar"|"final_exam_schedule";const termRaw=String(formData.get("term")??"").toLowerCase();const term=(["spring","summer","fall"] as const).includes(termRaw as "spring"|"summer"|"fall") ? termRaw as "spring"|"summer"|"fall" : null;const year=Number(formData.get("year"));const title=String(formData.get("title")??"").trim();const file=formData.get("file");if(!['academic_calendar','final_exam_schedule'].includes(type)||!term||!year||!title||!(file instanceof File)||file.size===0) throw new Error("Please complete all document fields.");type AcademicDocumentMimeType="application/pdf"|"image/jpeg"|"image/png"|"image/webp"|"image/gif";const allowedTypes=["application/pdf","image/jpeg","image/png","image/webp","image/gif"] as const;const isAcademicDocumentMimeType=(value:string):value is AcademicDocumentMimeType => allowedTypes.includes(value as AcademicDocumentMimeType);if(!isAcademicDocumentMimeType(file.type)) throw new Error("Only PDF or image files are allowed.");if(file.size>30*1024*1024) throw new Error("File must be 30MB or smaller.");const admin=createAdminClient();const {data:oldDoc}=await admin.from("academic_documents").select("storage_path").eq("document_type",type).eq("term",term).eq("year",year).maybeSingle();const ext=(file.name.split(".").pop()||"bin").toLowerCase().replace(/[^a-z0-9]/g,"")||"bin";const path=`${type}/${term}-${year}-${Date.now()}.${ext}`;const bytes=new Uint8Array(await file.arrayBuffer());const {error:uploadError}=await admin.storage.from("admin-documents").upload(path,bytes,{contentType:file.type,upsert:false});if(uploadError) throw new Error(uploadError.message);const {error:dbError}=await admin.from("academic_documents").upsert({document_type:type,term:term as any,year,title,storage_path:path,mime_type:file.type,file_size_bytes:file.size,uploaded_by:user.id,is_active:true},{onConflict:"document_type,term,year"});if(dbError){await admin.storage.from("admin-documents").remove([path]);throw new Error(dbError.message);}if(oldDoc?.storage_path&&oldDoc.storage_path!==path) await admin.storage.from("admin-documents").remove([oldDoc.storage_path]);revalidatePath("/admin/academic-tools/calendar");revalidatePath("/tools/academic-calendar");revalidatePath("/tools/final-exams"); redirect("/admin/academic-tools/calendar?saved=Academic%20document%20saved");}

export async function createDeadline(formData:FormData){const user=await requireAdmin();const admin=createAdminClient();const title=String(formData.get("title")??"").trim();const description=String(formData.get("description")??"").trim();const category=String(formData.get("category")??"Academic").trim();const term=String(formData.get("term")??"").trim().toLowerCase()||null;const yearRaw=String(formData.get("year")??"").trim();const dueAt=String(formData.get("due_at")??"").trim();const link=String(formData.get("link")??"").trim();if(title.length<3||!dueAt) throw new Error("Title and due date are required.");const {error}=await admin.from("deadlines").insert({title,description:description||null,category,term:term as any,year:yearRaw?Number(yearRaw):null,due_at:new Date(dueAt).toISOString(),link:link||null,is_active:true,created_by:user.id});if(error) throw new Error(error.message);revalidatePath("/admin/academic-tools/deadlines");revalidatePath("/tools/deadlines"); redirect("/admin/academic-tools/deadlines?saved=Deadline%20saved");}

export async function deleteDeadline(formData:FormData){await requireAdmin();const admin=createAdminClient();const id=String(formData.get("id")??"");await admin.from("deadlines").delete().eq("id",id);revalidatePath("/admin/academic-tools/deadlines");revalidatePath("/tools/deadlines"); redirect("/admin/academic-tools/deadlines?saved=Deadline%20deleted");}


export async function createAnnouncement(formData:FormData){const user=await requireAdmin();const admin=createAdminClient();const title=String(formData.get("title")??"").trim();const body=String(formData.get("body")??"").trim();const badge=String(formData.get("badge")??"").trim();const ctaLabel=String(formData.get("cta_label")??"").trim();const ctaLink=String(formData.get("cta_link")??"").trim();const starts=String(formData.get("starts_at")??"").trim();const ends=String(formData.get("ends_at")??"").trim();const priority=Number(formData.get("priority")??0);if(title.length<3||body.length<3) throw new Error("Title and message are required.");const {error}=await admin.from("announcements").insert({title,body,badge:badge||null,cta_label:ctaLabel||null,cta_link:ctaLink||null,starts_at:starts?new Date(starts).toISOString():null,ends_at:ends?new Date(ends).toISOString():null,is_active:true,priority,created_by:user.id});if(error) throw new Error(error.message);revalidatePath("/admin/academic-tools");revalidatePath("/"); redirect("/admin/academic-tools?saved=Announcement%20saved");}

export async function toggleAnnouncement(formData:FormData){await requireAdmin();const admin=createAdminClient();const id=String(formData.get("id"));const active=String(formData.get("active"))!=="true";await admin.from("announcements").update({is_active:active}).eq("id",id);revalidatePath("/admin/academic-tools");revalidatePath("/"); redirect("/admin/academic-tools?saved=Announcement%20status%20updated");}

export async function updateRequestStatus(formData:FormData){await requireAdmin();const admin=createAdminClient();const id=String(formData.get("id"));const status=String(formData.get("status"));const note=String(formData.get("admin_note")??"").trim();const returnTo=String(formData.get("return_to")??"").trim();if(!['open','in_progress','fulfilled','closed'].includes(status)) throw new Error("Invalid status");const {data:req}=await admin.from("resource_requests").select("user_id,title").eq("id",id).single();const {error}=await admin.from("resource_requests").update({status:status as any,admin_note:note||null}).eq("id",id);if(error) throw new Error(error.message);if(req){await admin.from("notifications").insert({profile_id:req.user_id,type:"resource_request_update",title:"Resource request updated",body:`${req.title} is now ${status.replace("_"," ")}.`,link:"/tools/resource-request"});}revalidatePath("/admin/academic-tools");revalidatePath("/admin/academic-tools/requests");revalidatePath("/admin/student-tools/resource-requests");revalidatePath("/tools/resource-request");redirect(`${returnTo || "/admin/academic-tools/requests"}?saved=Resource%20request%20updated`);}

export async function createHomepageBanner(formData: FormData) {
  const user = await requireAdmin(); const admin = createAdminClient();
  const title=String(formData.get("title")??"").trim(), body=String(formData.get("body")??"").trim();
  const badge=String(formData.get("badge")??"").trim(); const ctaRaw=String(formData.get("cta_link")??"").trim(); const custom=String(formData.get("custom_cta_link")??"").trim(); const ctaLink=ctaRaw==="custom"?custom:ctaRaw;
  const audience=String(formData.get("audience")??"all");
  const rawStatus=String(formData.get("status")??"draft"), status:BannerStatus=rawStatus==="published"||rawStatus==="scheduled"||rawStatus==="hidden"?rawStatus:"draft";
  const publishMode=String(formData.get("publish_mode")??"exact_dates");
  const startBehavior=String(formData.get("start_behavior")??"now");
  const rawDuration=Number(formData.get("duration_days")??7);
  const durationDays=Number.isFinite(rawDuration)?Math.max(1,Math.min(365,Math.round(rawDuration))):7;
  const rawStarts=String(formData.get("starts_at")??"").trim(), rawEnds=String(formData.get("ends_at")??"").trim();
  let starts=rawStarts, ends=rawEnds;
  if(publishMode==="duration" && status!=="draft" && status!=="hidden"){
    const startDate=startBehavior==="scheduled"&&rawStarts?new Date(rawStarts):new Date();
    if(Number.isNaN(startDate.getTime())) throw new Error("Invalid banner start date/time.");
    if(status==="published" || status==="scheduled"){
      starts=startDate.toISOString();
      ends=new Date(startDate.getTime()+durationDays*24*60*60*1000).toISOString();
    }
  }
  if(publishMode!=="exact_dates"&&publishMode!=="duration") throw new Error("Invalid publish mode.");
  if(startBehavior!=="now"&&startBehavior!=="scheduled") throw new Error("Invalid start behavior.");
  const order=Number(formData.get("display_order")??100); const dismissible=String(formData.get("is_dismissible")??"")==="true"; const frequency=String(formData.get("display_frequency")??"every_visit");
  const departmentId=String(formData.get("target_department_id")??"").trim()||null, courseId=String(formData.get("target_course_id")??"").trim()||null, alt=String(formData.get("image_alt")??"").trim()||title;
  const file=formData.get("image_file"), mobileFile=formData.get("mobile_image_file");
  if(title.length<3||body.length<3) throw new Error("Banner title and message are required.");
  if(!["all","student","seller","admin"].includes(audience)) throw new Error("Invalid audience.");
  if(!["draft","scheduled","published","hidden"].includes(status)) throw new Error("Invalid banner status.");
  if(!["every_visit","once_per_session","once_per_day"].includes(frequency)) throw new Error("Invalid display frequency.");
  if(starts&&ends&&new Date(starts).getTime()>=new Date(ends).getTime()) throw new Error("End time must be after start time.");
  if(publishMode==="duration" && status!=="draft" && status!=="hidden" && durationDays<1) throw new Error("Duration must be at least 1 day.");
  if(!(file instanceof File)||!file.size) throw new Error("Desktop banner image is required.");
  const allowed=new Set(["image/jpeg","image/png","image/webp","image/gif"]); if(!allowed.has(file.type)||file.size>8*1024*1024) throw new Error("Banner images must be JPG, PNG, WEBP or GIF and 8MB or smaller.");
  if(mobileFile instanceof File&&mobileFile.size&&!allowed.has(mobileFile.type)) throw new Error("Invalid mobile banner image type.");
  const upload=async(input:File,kind:"desktop"|"mobile")=>{const ext=(input.name.split(".").pop()||"jpg").replace(/[^a-z0-9]/gi,"")||"jpg";const path=`${audience}/${kind}/${crypto.randomUUID()}.${ext}`;const {error}=await admin.storage.from("homepage-banners").upload(path,new Uint8Array(await input.arrayBuffer()),{contentType:input.type,upsert:false});if(error)throw new Error(error.message);return {path,url:admin.storage.from("homepage-banners").getPublicUrl(path).data.publicUrl};};
  const desktop=await upload(file,"desktop"); let mobile:null|{path:string;url:string}=null;
  try{if(mobileFile instanceof File&&mobileFile.size)mobile=await upload(mobileFile,"mobile");const {error}=await admin.from("announcements").insert({title,body,badge:badge||null,cta_label:String(formData.get("cta_label")??"").trim()||null,cta_link:ctaLink||null,image_url:desktop.url,image_storage_path:desktop.path,mobile_image_url:mobile?.url??null,mobile_image_storage_path:mobile?.path??null,image_alt:alt,starts_at:starts?new Date(starts).toISOString():null,ends_at:ends?new Date(ends).toISOString():null,is_active:status!=="hidden"&&status!=="draft",priority:order,display_order:order,status,audience:audience as any,is_dismissible:dismissible,display_frequency:frequency as any,publish_mode:publishMode as any,duration_days:publishMode==="duration"?durationDays:null,target_department_id:departmentId,target_course_id:courseId,created_by:user.id,updated_by:user.id});if(error)throw new Error(error.message);}catch(e){await admin.storage.from("homepage-banners").remove([desktop.path,...(mobile?[mobile.path]:[])]);throw e;}
  revalidatePath("/admin/academic-tools/banners"); revalidatePath("/"); redirect("/admin/academic-tools/banners?saved=Homepage%20banner%20created");
}

export async function updateHomepageBanner(formData: FormData) {
  const user=await requireAdmin(); const admin=createAdminClient(); const id=String(formData.get("id")??"");
  const title=String(formData.get("title")??"").trim(), body=String(formData.get("body")??"").trim(); const badge=String(formData.get("badge")??"").trim(); const ctaRaw=String(formData.get("cta_link")??"").trim(); const custom=String(formData.get("custom_cta_link")??"").trim(); const ctaLink=ctaRaw==="custom"?custom:ctaRaw;
  const audience=String(formData.get("audience")??"all"); const rawStatus=String(formData.get("status")??"draft"), status:BannerStatus=rawStatus==="published"||rawStatus==="scheduled"||rawStatus==="hidden"?rawStatus:"draft";
  const publishMode=String(formData.get("publish_mode")??"exact_dates"); const startBehavior=String(formData.get("start_behavior")??"now"); const rawDuration=Number(formData.get("duration_days")??7); const durationDays=Number.isFinite(rawDuration)?Math.max(1,Math.min(365,Math.round(rawDuration))):7;
  const rawStarts=String(formData.get("starts_at")??"").trim(), rawEnds=String(formData.get("ends_at")??"").trim(); let starts=rawStarts, ends=rawEnds;
  if(publishMode==="duration" && status!=="draft" && status!=="hidden"){ const startDate=startBehavior==="scheduled"&&rawStarts?new Date(rawStarts):new Date(); if(Number.isNaN(startDate.getTime())) throw new Error("Invalid banner start date/time."); starts=startDate.toISOString(); ends=new Date(startDate.getTime()+durationDays*24*60*60*1000).toISOString(); }
  if(publishMode!=="exact_dates"&&publishMode!=="duration") throw new Error("Invalid publish mode."); if(startBehavior!=="now"&&startBehavior!=="scheduled") throw new Error("Invalid start behavior.");
  const order=Number(formData.get("display_order")??100); const dismissible=String(formData.get("is_dismissible")??"")==="true"; const frequency=String(formData.get("display_frequency")??"every_visit"); const dept=String(formData.get("target_department_id")??"").trim()||null, course=String(formData.get("target_course_id")??"").trim()||null;
  if(!id||title.length<3||body.length<3) throw new Error("Banner id, title and message are required."); if(starts&&ends&&new Date(starts).getTime()>=new Date(ends).getTime()) throw new Error("End time must be after start time."); if(publishMode==="duration"&&durationDays<1) throw new Error("Duration must be at least 1 day.");
  const {data:existing}=await admin.from("announcements").select("image_storage_path,mobile_image_storage_path").eq("id",id).single(); const patch:any={title,body,badge:badge||null,cta_label:String(formData.get("cta_label")??"").trim()||null,cta_link:ctaLink||null,audience:audience as any,starts_at:starts?new Date(starts).toISOString():null,ends_at:ends?new Date(ends).toISOString():null,status,is_active:status!=="hidden"&&status!=="draft",priority:order,display_order:order,is_dismissible:dismissible,display_frequency:frequency as any,publish_mode:publishMode as any,duration_days:publishMode==="duration"?durationDays:null,target_department_id:dept,target_course_id:course,image_alt:String(formData.get("image_alt")??"").trim()||title,updated_by:user.id};
  const allowed=new Set(["image/jpeg","image/png","image/webp","image/gif"]); const upload=async(input:File,kind:"desktop"|"mobile")=>{if(!allowed.has(input.type)||input.size>8*1024*1024)throw new Error("Banner images must be JPG, PNG, WEBP or GIF and 8MB or smaller.");const ext=(input.name.split(".").pop()||"jpg").replace(/[^a-z0-9]/gi,"")||"jpg";const path=`${audience}/${kind}/${crypto.randomUUID()}.${ext}`;const {error}=await admin.storage.from("homepage-banners").upload(path,new Uint8Array(await input.arrayBuffer()),{contentType:input.type,upsert:false});if(error)throw new Error(error.message);return {path,url:admin.storage.from("homepage-banners").getPublicUrl(path).data.publicUrl};};
  const created:string[]=[]; try{const f=formData.get("image_file"),m=formData.get("mobile_image_file");if(f instanceof File&&f.size){const x=await upload(f,"desktop");created.push(x.path);patch.image_url=x.url;patch.image_storage_path=x.path;}if(m instanceof File&&m.size){const x=await upload(m,"mobile");created.push(x.path);patch.mobile_image_url=x.url;patch.mobile_image_storage_path=x.path;}const {error}=await admin.from("announcements").update(patch).eq("id",id);if(error)throw new Error(error.message);}catch(e){if(created.length)await admin.storage.from("homepage-banners").remove(created);throw e;}
  const oldPaths=[patch.image_storage_path&&existing?.image_storage_path,patch.mobile_image_storage_path&&existing?.mobile_image_storage_path].filter(Boolean) as string[];if(oldPaths.length)await admin.storage.from("homepage-banners").remove(oldPaths);revalidatePath("/admin/academic-tools/banners");revalidatePath("/");redirect("/admin/academic-tools/banners?saved=Homepage%20banner%20updated");
}

export async function deleteHomepageBanner(formData:FormData){await requireAdmin();const admin=createAdminClient();const id=String(formData.get("id")??"");const {data:b}=await admin.from("announcements").select("image_storage_path,mobile_image_storage_path").eq("id",id).maybeSingle();const paths=[b?.image_storage_path,b?.mobile_image_storage_path].filter(Boolean) as string[];if(paths.length)await admin.storage.from("homepage-banners").remove(paths);await admin.from("announcements").delete().eq("id",id);revalidatePath("/admin/academic-tools/banners");revalidatePath("/");redirect("/admin/academic-tools/banners?saved=Homepage%20banner%20deleted");}

export async function reorderHomepageBanners(ids:string[]){await requireAdmin();const admin=createAdminClient();for(let i=0;i<ids.length;i++){await admin.from("announcements").update({display_order:i+1,priority:i+1}).eq("id",ids[i]);}revalidatePath("/admin/academic-tools/banners");revalidatePath("/");}
export async function saveBannerAudienceSettings(formData:FormData){await requireAdmin();const admin=createAdminClient();const audience=String(formData.get("audience")??"all");const max_visible=Math.max(1,Math.min(10,Number(formData.get("max_visible")??5)));const autoplay=String(formData.get("autoplay"))==="true";const auto_rotate_seconds=Math.max(3,Math.min(20,Number(formData.get("auto_rotate_seconds")??6)));const show_dots=String(formData.get("show_dots"))==="true";const show_arrows=String(formData.get("show_arrows"))==="true";const transition=String(formData.get("transition")??"fade_slide");const {error}=await admin.from("homepage_banner_settings").upsert({audience:audience as any,max_visible,autoplay,auto_rotate_seconds,show_dots,show_arrows,transition:transition as any,updated_at:new Date().toISOString()});if(error)throw new Error(error.message);revalidatePath("/admin/academic-tools/banners");revalidatePath("/");redirect("/admin/academic-tools/banners?saved=Banner%20display%20settings%20saved");}
