export default function PrivacyPolicy() {
  return (
    <>
      <h1>Privacy Policy</h1>
      <p>Last updated: {new Date().toLocaleDateString()}</p>
      <p>
        EWU StudyHub collects the information you provide when you create an
        account (name, username, university email, department, semester,
        batch) and information generated by your use of the platform
        (uploads, purchases, reviews, download history).
      </p>
      <h2>How we use your data</h2>
      <ul>
        <li>To verify your student status and enable marketplace features</li>
        <li>To process purchases and pay out seller earnings</li>
        <li>To personalize recommendations and search results</li>
        <li>To detect fraud, spam, and policy violations</li>
      </ul>
      <h2>What we share</h2>
      <p>
        Your public profile (name, username, avatar, badges) is visible to
        other users. Payment details are handled by our payment gateway
        partners (bKash, Nagad, Rocket) and are not stored on our servers
        beyond a transaction reference.
      </p>
      <h2>Your rights</h2>
      <p>
        You may request a copy of your data or account deletion by contacting
        support. Deleting your account removes your public profile; purchase
        records are retained as required for financial recordkeeping.
      </p>
    </>
  );
}
