"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { CalendarClock, CheckCircle2, Clock3, FileQuestion, Megaphone, MessageSquare, ShieldAlert, ShoppingBag, WalletCards, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { markNotificationRead } from "@/app/notifications/actions";

type NotificationItem={id:string;type:string;title:string;body:string|null;link:string|null;is_read:boolean;created_at:string};
const filters=["all","unread","marketplace","seller","system"] as const;
function category(type:string){if(["purchase_completed","purchase_pending","purchase_approved","purchase_rejected"].includes(type)) return "marketplace";if(["payout_completed","payout_requested","payment_submitted","seller_approved","seller_rejected"].includes(type)) return "seller";return "system";}
function icon(type:string){if(type.includes("purchase")) return <ShoppingBag className="h-5 w-5 text-primary"/>;if(type.includes("payout")) return <WalletCards className="h-5 w-5 text-primary"/>;if(type.includes("deadline")) return <CalendarClock className="h-5 w-5 text-amber-500"/>;if(type.includes("resource_request")) return <FileQuestion className="h-5 w-5 text-sky-500"/>;if(type.includes("announcement")) return <Megaphone className="h-5 w-5 text-primary"/>;if(type.includes("admin_message")) return <MessageSquare className="h-5 w-5 text-violet-500"/>;if(type.includes("rejected")||type==="report_update") return <XCircle className="h-5 w-5 text-destructive"/>;if(type.includes("approved")||type.includes("completed")) return <CheckCircle2 className="h-5 w-5 text-primary"/>;return <Clock3 className="h-5 w-5 text-amber-500"/>;}
export function NotificationList({notifications}:{notifications:NotificationItem[]}){const [filter,setFilter]=useState<typeof filters[number]>("all");const visible=useMemo(()=>notifications.filter(n=>filter==="all"||(filter==="unread"&&!n.is_read)||category(n.type)===filter),[filter,notifications]);return <div className="mt-6"><div className="flex flex-wrap gap-2 pb-2">{filters.map(f=><button key={f} type="button" onClick={()=>setFilter(f)} className={`rounded-full border px-3 py-1.5 text-xs font-semibold capitalize ${filter===f?"border-primary bg-primary/10 text-primary":"hover:bg-accent"}`}>{f}</button>)}</div><div className="mt-4 space-y-3">{visible.length?visible.map(n=><Card key={n.id} className={!n.is_read?"border-primary/40 bg-primary/[0.03]":""}><CardContent className="flex gap-3 p-4 sm:gap-4"><div className="mt-0.5 flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-muted/70">{icon(n.type)}</div><div className="min-w-0 flex-1"><div className="flex items-start gap-2"><div className="min-w-0 flex-1"><p className="font-semibold leading-5">{n.title}</p><p className="mt-0.5 text-xs text-muted-foreground">{new Date(n.created_at).toLocaleString()}</p></div>{!n.is_read&&<span className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-primary" aria-label="Unread"/>}</div>{n.body&&<p className="mt-2 text-sm leading-6 text-muted-foreground">{n.body}</p>}<div className="mt-3 flex flex-wrap gap-2">{n.link&&<Button asChild size="sm" variant="outline"><Link href={n.link}>Open</Link></Button>}{!n.is_read&&<form action={markNotificationRead}><input type="hidden" name="notification_id" value={n.id}/><Button type="submit" size="sm" variant="ghost">Mark as read</Button></form>}</div></div></CardContent></Card>):<Card><CardContent className="flex flex-col items-center p-10 text-center"><ShieldAlert className="h-7 w-7 text-muted-foreground"/><p className="mt-3 font-medium">Nothing here</p><p className="mt-1 text-sm text-muted-foreground">Try another notification filter.</p></CardContent></Card>}</div></div>}
