import { CalendarClock, ExternalLink } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

function fmt(date:string){return new Date(date).toLocaleString("en-BD",{dateStyle:"medium",timeStyle:"short"});}
export default async function DeadlinesPage(){const supabase=createClient();const {data}=await supabase.from("deadlines").select("id,title,description,category,term,year,due_at,link").eq("is_active",true).order("due_at",{ascending:true}).limit(100);const now=Date.now();return <div className="flex min-h-screen flex-col"><Navbar/><main className="container flex-1 py-8 sm:py-12"><div className="max-w-2xl"><p className="text-sm font-semibold text-primary">Stay on track</p><h1 className="mt-1 text-3xl font-bold">Deadline Tracker</h1><p className="mt-2 text-sm text-muted-foreground">Important academic and StudyHub deadlines, ordered by what is due next.</p></div><div className="mt-8 space-y-3">{data?.length?data.map(d=>{const days=Math.ceil((new Date(d.due_at).getTime()-now)/86400000);return <Card key={d.id} className={days<0?"opacity-60":""}><CardContent className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><CalendarClock className="h-5 w-5"/></div><div className="min-w-0"><div className="flex flex-wrap gap-2"><span className="rounded-full border px-2 py-0.5 text-[11px] font-semibold">{d.category}</span>{d.term&&<span className="rounded-full bg-muted px-2 py-0.5 text-[11px]">{d.term} {d.year}</span>}</div><p className="mt-2 font-semibold">{d.title}</p>{d.description&&<p className="mt-1 text-sm text-muted-foreground">{d.description}</p>}</div></div><div className="shrink-0 sm:text-right"><p className={`font-semibold ${days>=0&&days<=3?"text-amber-600 dark:text-amber-300":""}`}>{days<0?"Passed":days===0?"Due today":`${days} day${days===1?"":"s"} left`}</p><p className="text-xs text-muted-foreground">{fmt(d.due_at)}</p>{d.link&&<Button asChild variant="link" size="sm" className="mt-1 px-0"><a href={d.link} target="_blank" rel="noreferrer">Open source <ExternalLink className="h-3 w-3"/></a></Button>}</div></CardContent></Card>}) : <Card><CardContent className="p-10 text-center text-sm text-muted-foreground">No deadlines have been added yet.</CardContent></Card>}</div></main><Footer/></div>}
