-- 0007_full_course_catalog.sql
-- Adds credit tracking to courses, and seeds the full EWU department/course catalog
-- (Phase A of course-catalog integration -- see conversation for scope).

alter table courses add column if not exists credit numeric(4,2);

-- Departments (13 degree programs + 2 shared buckets for cross-listed / gen-ed courses)
insert into departments (university_id, name, short_name)
select id, dept.name, dept.short_name
from universities, (values
  ('Computer Science & Engineering', 'CSE'),
  ('Electrical & Electronic Engineering', 'EEE'),
  ('Business Administration', 'BBA'),
  ('English', 'ENG'),
  ('Applied Statistics', 'AST'),
  ('Economics', 'ECO'),
  ('Electronic & Telecommunication Engineering', 'ETE'),
  ('Genetic Engineering & Biotechnology', 'GEB'),
  ('General Education', 'GENED'),
  ('Information & Communication Engineering', 'ICE'),
  ('Information Studies & Library Management', 'ISLM'),
  ('Law', 'LAW'),
  ('Mathematics & Basic Sciences', 'MBS'),
  ('Pharmacy', 'PHRM'),
  ('Sociology', 'SOC')
) as dept(name, short_name)
where universities.short_name = 'EWU'
on conflict (university_id, short_name) do nothing;

-- Courses
insert into courses (department_id, course_code, course_name, credit)
select d.id, c.code, c.name, c.credit
from departments d, (values
  ('CSE', 'CSE101', 'Introduction to Computers', 3.0),
  ('CSE', 'CSE102', 'Introduction to Computers', 3.0),
  ('CSE', 'CSE103', 'Structured Programming', 4.5),
  ('CSE', 'CSE106', 'Discrete Mathematics', 3.0),
  ('CSE', 'CSE110', 'Object Oriented Programming', 4.5),
  ('CSE', 'CSE200', 'Computer-Aided Engineering Drawing', 1.0),
  ('CSE', 'CSE209', 'Electrical Circuits', 4.0),
  ('CSE', 'CSE207', 'Data Structures', 4.0),
  ('CSE', 'CSE251', 'Electronic Circuits', 4.0),
  ('CSE', 'CSE221', 'Operating Systems', 4.0),
  ('CSE', 'CSE326', 'Algorithms', 4.5),
  ('CSE', 'CSE302', 'Database Systems', 4.5),
  ('CSE', 'CSE345', 'Digital Logic Design', 4.0),
  ('CSE', 'CSE347', 'Information System Analysis and Design', 4.0),
  ('CSE', 'CSE360', 'Computer Architecture', 3.0),
  ('CSE', 'CSE405', 'Computer Networks', 4.0),
  ('CSE', 'CSE407', 'Green Computing', 3.0),
  ('CSE', 'CSE487', 'Cyber Security, Ethics and Law', 3.0),
  ('CSE', 'CSE495', 'IT Project Management and Entrepreneurship', 3.0),
  ('CSE', 'CSE400', 'Capstone Project', 6.0),
  ('CSE', 'CSE303', 'Statistics for Data Science', 4.0),
  ('CSE', 'CSE366', 'Artificial Intelligence', 4.0),
  ('CSE', 'CSE420', 'Computer Graphics', 4.0),
  ('CSE', 'CSE438', 'Digital Image Processing', 4.0),
  ('CSE', 'CSE445', 'Computer Vision', 4.0),
  ('CSE', 'CSE452', 'Distributed Systems and Algorithms', 4.0),
  ('CSE', 'CSE474', 'Pattern Recognition', 4.0),
  ('CSE', 'CSE475', 'Machine Learning', 4.0),
  ('CSE', 'CSE477', 'Data Mining', 4.0),
  ('CSE', 'CSE481', 'Nature-Inspired Computing', 4.0),
  ('CSE', 'CSE486', 'Bioinformatics Algorithms', 4.0),
  ('CSE', 'CSE488', 'Big Data Analytics', 4.0),
  ('CSE', 'CSE412', 'Software Engineering', 4.0),
  ('CSE', 'CSE430', 'Software Testing and Quality Assurance', 4.0),
  ('CSE', 'CSE422', 'Simulation and Modeling', 4.0),
  ('CSE', 'CSE423', 'Software Architecture', 4.0),
  ('CSE', 'CSE428', 'Human Computer Interactions', 4.0),
  ('CSE', 'CSE464', 'Advanced Database System', 4.0),
  ('CSE', 'CSE479', 'Web Programming', 4.0),
  ('CSE', 'CSE489', 'Mobile Programming', 4.0),
  ('CSE', 'CSE350', 'Data Communications', 4.0),
  ('CSE', 'CSE432', 'Digital Signal Processing', 4.0),
  ('CSE', 'CSE453', 'Wireless Networks', 4.0),
  ('CSE', 'CSE457', 'Cellular Networks', 4.0),
  ('CSE', 'CSE472', 'Advanced Network Services and Management', 4.0),
  ('CSE', 'CSE473', 'Network Security and Systems', 4.0),
  ('CSE', 'CSE355', 'Digital System Design', 4.0),
  ('CSE', 'CSE442', 'Microprocessors and Microcontrollers', 4.0),
  ('CSE', 'CSE406', 'Internet of Things', 4.0),
  ('CSE', 'CSE446', 'ASIC Design Using FPGA', 4.0),
  ('CSE', 'CSE491', 'VLSI Design', 4.0),
  ('CSE', 'CSE492', 'Robotics', 4.0),
  ('CSE', 'CSE494', 'Embedded Systems', 4.0),
  ('CSE', 'CSE225', 'Numerical Methods', 4.0),
  ('CSE', 'CSE313', 'Theory of Computations', 3.0),
  ('CSE', 'CSE460', 'Cryptography', 3.0),
  ('CSE', 'CSE471', 'Compiler Design', 4.0),
  ('CSE', 'CSE483', 'Graph Theory', 3.0),
  ('CSE', 'CSE484', 'Computational Geometry', null),
  ('CSE', 'CSE436', 'Multimedia Design and Development', 3.0),
  ('CSE', 'CSE450', 'Data Structure and Algorithm', 4.0),
  ('CSE', 'CSE108', 'Computer and Software Fundamentals', 4.0),
  ('CSE', 'CSE205', 'Discrete Mathematics', 3.0),
  ('EEE', 'EEE399', 'Engineering Project Management', 3.0),
  ('EEE', 'EEE101', 'Electrical Circuits I', 4.0),
  ('EEE', 'EEE102', 'Electronic Circuits I', 4.0),
  ('EEE', 'EEE105', 'Computer Programming', 4.0),
  ('EEE', 'EEE201', 'Electrical Circuits II', 4.0),
  ('EEE', 'EEE202', 'Electronic Circuits II', 4.0),
  ('EEE', 'EEE204', 'Numerical Analysis for Electrical Engineering', 4.0),
  ('EEE', 'EEE205', 'Digital Logic Design', 4.0),
  ('EEE', 'EEE300', 'Electrical Services Design', 3.0),
  ('EEE', 'EEE301', 'Electrical Machines', 4.0),
  ('EEE', 'EEE302', 'Microprocessors and Interfacing', 4.0),
  ('EEE', 'EEE303', 'Signals and Linear Systems', 3.0),
  ('EEE', 'EEE304', 'Electrical Power Systems', 4.0),
  ('EEE', 'EEE305', 'Electromagnetic Fields and Waves', 3.0),
  ('EEE', 'EEE307', 'Telecommunication Engineering', 4.0),
  ('EEE', 'EEE308', 'Electronic Properties of Materials', 3.0),
  ('EEE', 'EEE309', 'Digital Signal Processing', 4.0),
  ('EEE', 'EEE402', 'Control Systems', 4.0),
  ('EEE', 'EEE403', 'Engineer and Society', 3.0),
  ('EEE', 'EEE413', 'Fundamentals of Nanotechnology', 3.0),
  ('EEE', 'EEE414', 'Optoelectronics', 3.0),
  ('EEE', 'EEE415', 'Semiconductor Processing and Fabrication', 4.0),
  ('EEE', 'EEE416', 'VLSI Circuits and Systems', 4.0),
  ('EEE', 'EEE417', 'Semiconductor Devices', 3.0),
  ('EEE', 'EEE418', 'Analog Integrated Circuits', 4.0),
  ('EEE', 'EEE419', 'Biomedical Electronics', 3.0),
  ('EEE', 'EEE421', 'RF and Microwave Engineering', 4.0),
  ('EEE', 'EEE422', 'Digital Communications', 4.0),
  ('EEE', 'EEE423', 'Wireless and Mobile Communications', 4.0),
  ('EEE', 'EEE425', 'Digital Image Processing', 3.0),
  ('EEE', 'EEE426', 'Advanced Telecommunication Engineering', 3.0),
  ('EEE', 'EEE433', 'Computer Networks', 4.0),
  ('EEE', 'EEE434', 'Computer Architecture', 4.0),
  ('EEE', 'EEE435', 'Embedded Systems', 4.0),
  ('EEE', 'EEE441', 'Power Stations', 3.0),
  ('EEE', 'EEE442', 'Switchgear and Protective Relays', 4.0),
  ('EEE', 'EEE444', 'High Voltage Engineering', 3.0),
  ('EEE', 'EEE445', 'Renewable Energy', 3.0),
  ('EEE', 'EEE446', 'Power System Operation and Reliability', 3.0),
  ('EEE', 'EEE447', 'Power Electronics', 4.0),
  ('EEE', 'EEE450', 'Special Topic in Electrical and Electronic Engineering', 3.0),
  ('EEE', 'EEE490', 'Research Project', 3.0),
  ('EEE', 'EEE400A', 'Final Year Design Project (Part 1 of 3)', 1.0),
  ('EEE', 'EEE400B', 'Final Year Design Project (Part 2 of 3)', 2.0),
  ('EEE', 'EEE400C', 'Final Year Design Project (Part 3 of 3)', 3.0),
  ('BBA', 'BUS101', 'Introduction to Business', 3.0),
  ('BBA', 'BUS301', 'Business Ethics', 3.0),
  ('BBA', 'MGT321', 'Industrial Management (For the student of FSE)', 3.0),
  ('BBA', 'ACT101', 'Financial Accounting', 3.0),
  ('BBA', 'ACT201', 'Management Accounting', 3.0),
  ('BBA', 'BUS231', 'Business Communication', 3.0),
  ('BBA', 'BUS361', 'Legal Environment of Business', 3.0),
  ('BBA', 'FIN101', 'Principles of Finance', 3.0),
  ('BBA', 'FIN201', 'Business Finance', 3.0),
  ('BBA', 'ITB301', 'International Business', 3.0),
  ('BBA', 'MGT101', 'Principles of Management', 3.0),
  ('BBA', 'MGT251', 'Organizational Behavior', 3.0),
  ('BBA', 'MGT337', 'Production Operations Management', 3.0),
  ('BBA', 'HRM301', 'Human Resources Management', 3.0),
  ('BBA', 'MGT480', 'Strategic Management', 3.0),
  ('BBA', 'MIS101', 'Introduction to Management Information System', 3.0),
  ('BBA', 'MIS305', 'Enterprise Information System', 3.0),
  ('BBA', 'MKT101', 'Principles of Marketing', 3.0),
  ('BBA', 'MKT201', 'Marketing Management', 3.0),
  ('BBA', 'ACT311', 'Taxation', 3.0),
  ('BBA', 'ACT411', 'Intermediate Accounting-I', 3.0),
  ('BBA', 'ACT421', 'Intermediate Accounting-II', 3.0),
  ('BBA', 'ACT441', 'Cost Accounting', 3.0),
  ('BBA', 'ACT427', 'Auditing', 3.0),
  ('BBA', 'ACT430', 'Accounting Information System', 3.0),
  ('BBA', 'ACT456', 'Accounting Theory', 3.0),
  ('BBA', 'ACT478', 'Advanced Accounting', 3.0),
  ('BBA', 'FIN425', 'Investment Analysis and Management', 3.0),
  ('BBA', 'FIN435', 'Managerial Finance', 3.0),
  ('BBA', 'FIN335', 'Financial Institutions and Markets', 3.0),
  ('BBA', 'FIN350', 'Real Estate Finance', 3.0),
  ('BBA', 'FIN380', 'Management of Commercial Bank', 3.0),
  ('BBA', 'FIN408', 'Financial Analysis and Control', 3.0),
  ('BBA', 'FIN410', 'Risk Management and Insurance', 3.0),
  ('BBA', 'FIN450', 'Cases in Financial Management', 3.0),
  ('BBA', 'FIN475', 'Option and Future', 3.0),
  ('BBA', 'ITB401', 'International Operations', 3.0),
  ('BBA', 'ITB445', 'International Financial Institution', 3.0),
  ('BBA', 'ITB450', 'International Businesses Negotiations', 3.0),
  ('BBA', 'ITB455', 'Country Risk Analysis', 3.0),
  ('BBA', 'ITB460', 'International Competitiveness', 3.0),
  ('BBA', 'MGT402', 'Management Science', 3.0),
  ('BBA', 'MGT421', 'Entrepreneurship Development', 3.0),
  ('BBA', 'MGT465', 'Leadership Management', 3.0),
  ('BBA', 'MGT405', 'Organizational Development and Change', 3.0),
  ('BBA', 'MGT410', 'International Labor Management', 3.0),
  ('BBA', 'MGT425', 'Total Quality Management', 3.0),
  ('BBA', 'MGT437', 'Small Business Management', 3.0),
  ('BBA', 'MGT448', 'Managing Globalization', 3.0),
  ('BBA', 'MIS401', 'Structured Programming', 3.0),
  ('BBA', 'MIS402', 'System Analysis and Design', 3.0),
  ('BBA', 'MIS404', 'Networking and Operating System', 3.0),
  ('BBA', 'MIS406', 'Relational Database Management Systems', 3.0),
  ('BBA', 'MIS403', 'Object Oriented Programming', 3.0),
  ('BBA', 'MIS407', 'System Integration & Security and Internet', 3.0),
  ('BBA', 'MIS408', 'Internetworking with TCP/IP and Implementing Exchange Server', 3.0),
  ('BBA', 'MIS409', 'Client/Server Administration', 3.0),
  ('BBA', 'MIS410', 'Database Systems', 3.0),
  ('BBA', 'MIS415', 'Decision Support Systems', 3.0),
  ('BBA', 'MIS419', 'E-Commerce and Web Programming', 3.0),
  ('BBA', 'MKT410', 'Consumer Behavior', 3.0),
  ('BBA', 'MKT414', 'Marketing Research', 3.0),
  ('BBA', 'MKT401', 'Sales Management', 3.0),
  ('BBA', 'MKT402', 'Integrated Marketing Communication', 3.0),
  ('BBA', 'MKT412', 'Service Marketing', 3.0),
  ('BBA', 'MKT411', 'Export-Import Management', 3.0),
  ('BBA', 'MKT416', 'Brand Management', 3.0),
  ('BBA', 'MKT418', 'Supply Chain Management', 3.0),
  ('BBA', 'MKT430', 'Strategic Marketing', 3.0),
  ('BBA', 'HRM411', 'Human Resource Planning', 3.0),
  ('BBA', 'HRM412', 'Compensation Management', 3.0),
  ('BBA', 'HRM413', 'Industrial Relations and Labour Law', 3.0),
  ('BBA', 'HRM415', 'Training and Development', 3.0),
  ('BBA', 'HRM416', 'Strategic Human Resource Management', 3.0),
  ('BBA', 'HRM417', 'Human Resource Information System', 3.0),
  ('BBA', 'HRM418', 'Job Analysis and Performance Appraisal', 3.0),
  ('BBA', 'HRM419', 'Leadership, Power and Influence', 3.0),
  ('BBA', 'HRM420', 'Organizational Development', 3.0),
  ('BBA', 'HRM421', 'International Human Resource Management', 3.0),
  ('BBA', 'BUS498', 'Project Work', 3.0),
  ('BBA', 'BUS499', 'Internship', 3.0),
  ('BBA', 'BUS321', 'Business for Engineering & Technology', 3.0),
  ('BBA', 'HRM414', 'Industrial Relations', 3.0),
  ('BBA', 'MKT406', 'Brand Management', 3.0),
  ('ENG', 'ENG100', 'Improving Oral Communication Skills', 3.0),
  ('ENG', 'ENG101', 'Basic English', 3.0),
  ('ENG', 'ENG102', 'Composition and Communication Skills', 3.0),
  ('ENG', 'ENG145', 'Introduction to Linguistics', 3.0),
  ('ENG', 'ENG154', 'English Phonetics and Phonology', 3.0),
  ('ENG', 'ENG155', 'Improving Reading and Writing Skills', 3.0),
  ('ENG', 'ENG191', 'Introduction to Literature: Fiction and Non-Fiction Prose', 3.0),
  ('ENG', 'ENG192', 'Introduction to Literature: Poetry and Drama', 3.0),
  ('ENG', 'ENG205', 'History of the English Language', 3.0),
  ('ENG', 'ENG207', 'Psycholinguistics', 3.0),
  ('ENG', 'ENG208', 'Sociolinguistics', 3.0),
  ('ENG', 'ENG209', 'Political and Social History of England', 3.0),
  ('ENG', 'ENG230', 'Nineteenth Century Novel', 3.0),
  ('ENG', 'ENG245', 'Romantic Poetry', 3.0),
  ('ENG', 'ENG301', 'Elizabethan and Restoration Drama', 3.0),
  ('ENG', 'ENG306', 'Methodology of Language Teaching', 3.0),
  ('ENG', 'ENG309', 'Advanced Reading and Writing', 3.0),
  ('ENG', 'ENG310', 'Shakespeare', 3.0),
  ('ENG', 'ENG315', 'Seventeenth and Eighteenth Century Poetry', 3.0),
  ('ENG', 'ENG403', 'Modern Novel', 3.0),
  ('ENG', 'ENG412', 'Techniques of Teaching English Language Skills', 3.0),
  ('ENG', 'ENG426', 'American Literature (Modern to Contemporary)', 3.0),
  ('ENG', 'ENG438', 'Literary Criticism', 3.0),
  ('ENG', 'ENG211', 'Representation of Women in Literature', 3.0),
  ('ENG', 'ENG213', 'English Satire', 3.0),
  ('ENG', 'ENG222', 'Introduction to Bangla Literature', 3.0),
  ('ENG', 'ENG320', 'Victorian Prose and Poetry', 3.0),
  ('ENG', 'ENG330', 'English Prose from Bacon to Swift', 3.0),
  ('ENG', 'ENG340', 'Eighteenth Century Fiction', 3.0),
  ('ENG', 'ENG410', 'Continental Literature', 3.0),
  ('ENG', 'ENG420', 'American Literature (1620-1891)', 3.0),
  ('ENG', 'ENG423', 'Old and Middle English', 3.0),
  ('ENG', 'ENG424', 'Classics in Translation', 3.0),
  ('ENG', 'ENG430', 'Cultural Studies', 3.0),
  ('ENG', 'ENG435', 'Postcolonial Theory and Literature', 3.0),
  ('ENG', 'ENG440', 'Literary Theory', 3.0),
  ('ENG', 'ENG445', 'Modern Poetry', 3.0),
  ('ENG', 'ENG450', 'Modern Drama', 3.0),
  ('ENG', 'ENG452', 'Contemporary Literature in English', 3.0),
  ('ENG', 'ENG455', 'Comparative Literature', 3.0),
  ('ENG', 'ENG458', 'Feminist Readings of Literature', 3.0),
  ('ENG', 'ENG200', 'Advanced Oral Communication Skills (Open elective)', 3.0),
  ('ENG', 'ENG201', 'Theories of Writing', 3.0),
  ('ENG', 'ENG226', 'Business and Professional Communication (Open elective)', 3.0),
  ('ENG', 'ENG235', 'Teaching Language through Literature', 3.0),
  ('ENG', 'ENG255', 'Second Language Acquisition (SLA)', 3.0),
  ('ENG', 'ENG303', 'Syllabus and Material Design', 3.0),
  ('ENG', 'ENG305', 'Linguistic Theories', 3.0),
  ('ENG', 'ENG307', 'Academic Writing', 3.0),
  ('ENG', 'ENG313', 'English for the Media (Open elective)', 3.0),
  ('ENG', 'ENG316', 'English for Specific Purposes', 3.0),
  ('ENG', 'ENG319', 'Translation Studies (Open elective)', 3.0),
  ('ENG', 'ENG402', 'Pragmatics and Discourse Analysis', 3.0),
  ('ENG', 'ENG405', 'Creative Writing', 3.0),
  ('ENG', 'ENG411', 'Language Acquisition Theories for EFL/ESL Contexts', 3.0),
  ('ENG', 'ENG413', 'Language Testing and Evaluation', 3.0),
  ('ENG', 'ENG414', 'Research Methodology in ELT', 3.0),
  ('ENG', 'ENG415', 'Language Policy and Planning', 3.0),
  ('ENG', 'ENG417', 'Problems & Prospects of ELT in Bangladesh', 3.0),
  ('ENG', 'ENG422', 'Bilingualism and EFL/ESL', 3.0),
  ('ENG', 'ENG436', 'ELT Research Project', 3.0),
  ('ENG', 'ENG451', 'Computer Assisted Language Learning/Teaching (CALL/CALT)', 3.0),
  ('AST', 'AST101', 'Introduction to Statistics', 3.0),
  ('AST', 'AST102', 'Elements of Probability', 3.0),
  ('AST', 'AST201', 'Probability Distributions', 3.0),
  ('AST', 'AST202', 'Sampling Distributions', 3.0),
  ('AST', 'AST203', 'Statistical Inference I', 3.0),
  ('AST', 'AST204', 'Agricultural Statistics and Design of Experiments', 3.0),
  ('AST', 'AST205', 'Introduction to Demography', 3.0),
  ('AST', 'AST206', 'Introductory Sampling Methods', 3.0),
  ('AST', 'AST207', 'Applied Statistical Analysis with R (Lab)', 3.0),
  ('AST', 'AST301', 'Design and Analysis of Factorial Experiments', 3.0),
  ('AST', 'AST302', 'Advanced Sampling Techniques', 3.0),
  ('AST', 'AST303', 'Statistical Inference II', 3.0),
  ('AST', 'AST304', 'Applied Regression Analysis', 3.0),
  ('AST', 'AST305', 'Introduction to Epidemiology', 3.0),
  ('AST', 'AST306', 'Population Studies', 3.0),
  ('AST', 'AST307', 'Social Statistics and Social Development', 3.0),
  ('AST', 'AST308', 'Statistical Analysis Using SPSS and SAS (Lab)', 3.0),
  ('AST', 'AST309', 'Applied Nonparametric Statistics', 3.0),
  ('AST', 'AST310', 'Categorical Data Analysis', 3.0),
  ('AST', 'AST401', 'Advanced Probability and Stochastic Process', 3.0),
  ('AST', 'AST402', 'Research Methodology', 4.0),
  ('AST', 'AST403', 'Applied Multivariate Data Analysis', 3.0),
  ('AST', 'AST404', 'Survival Analysis', 3.0),
  ('AST', 'AST405', 'Industrial Statistics and Operation Research', 3.0),
  ('AST', 'AST406', 'Modeling Time Series Data', 3.0),
  ('AST', 'AST407', 'Introduction to Generalized Linear Models', 3.0),
  ('AST', 'AST408', 'Life Contingencies', 3.0),
  ('AST', 'AST409', 'Bayesian Inference and Decision Theory', 3.0),
  ('AST', 'AST410', 'Statistical Analysis using STATA (Lab)', 3.0),
  ('AST', 'AST499', 'Project Report and Seminar', 3.0),
  ('ECO', 'ECO104', 'Introduction to Statistics', 3.0),
  ('ECO', 'ECO101', 'Principles of Microeconomics', 3.0),
  ('ECO', 'ECO102', 'Introduction to Macroeconomics', 3.0),
  ('ECO', 'ECO204', 'Statistics for Business and Economics', 3.0),
  ('ECO', 'ECO260', 'Environmental & Natural Resource Economics', 3.0),
  ('ECO', 'ECO301', 'Intermediate Microeconomic Theory I', 3.0),
  ('ECO', 'ECO302', 'Intermediate Macroeconomic Theory I', 3.0),
  ('ECO', 'ECO310', 'Money and Banking', 3.0),
  ('ECO', 'ECO315', 'Public Finance', 3.0),
  ('ECO', 'ECO328', 'International Trade and Finance', 3.0),
  ('ECO', 'ECO349', 'Economics of Development', 3.0),
  ('ECO', 'ECO360', 'Socio-Economic Profiles of Bangladesh', 3.0),
  ('ECO', 'ECO465', 'Basic Econometrics', 3.0),
  ('ECO', 'ECO467', 'Intermediate Microeconomic Theory II', 3.0),
  ('ECO', 'ECO475', 'History of Economic Thought', 3.0),
  ('ECO', 'ECO477', 'Intermediate Macroeconomic Theory II', 3.0),
  ('ECO', 'ECO490', 'Research Methodology', 3.0),
  ('ECO', 'ECO495', 'Supervised Research Paper', 3.0),
  ('ECO', 'ECO200', 'Agricultural Economics', 3.0),
  ('ECO', 'ECO220', 'Behavioral Economics', 3.0),
  ('ECO', 'ECO304', 'Economics of Health', 3.0),
  ('ECO', 'ECO312', 'Industrial Organization', 3.0),
  ('ECO', 'ECO314', 'Public Sector Economics', 3.0),
  ('ECO', 'ECO329', 'Contemporary Issues in International Economics', 3.0),
  ('ECO', 'ECO353', 'Economics of Development in South Asia', 3.0),
  ('ECO', 'ECO354', 'Environmental & Natural Resource Economics-II', 3.0),
  ('ECO', 'ECO355', 'Blue Economics', 3.0),
  ('ECO', 'ECO357', 'Mathematical Economics', 3.0),
  ('ECO', 'ECO375', 'Foundations in Financial Economics', 3.0),
  ('ECO', 'ECO382', 'Economic Valuation of Environment', 3.0),
  ('ECO', 'ECO406', 'International Economic Theory', 3.0),
  ('ECO', 'ECO414', 'Trade Policy Analysis', 3.0),
  ('ECO', 'ECO433', 'Gender and Development', 3.0),
  ('ECO', 'ECO443', 'Social Mobilization, Rural Banking & Community Organization', 3.0),
  ('ECO', 'ECO447', 'Applied Economics', 3.0),
  ('ECO', 'ECO449', 'Economics of Information', 3.0),
  ('ECO', 'ECO450', 'Labor Economics', 3.0),
  ('ECO', 'ECO453', 'Game Theory and Applications', 3.0),
  ('ECO', 'ECO455', 'Asian and Emerging Economies', 3.0),
  ('ECO', 'ECO460', 'Managerial Economics', 3.0),
  ('ECO', 'ECO461', 'Competition Law and Economics', 3.0),
  ('ECO', 'ECO474', 'Mathematical Economics II', 3.0),
  ('ECO', 'ECO480', 'Urban Economics', 3.0),
  ('ECO', 'ECO484', 'Project Analysis and Evaluation', 3.0),
  ('ECO', 'ECO485', 'Cost Benefit Analysis', 3.0),
  ('ECO', 'ECO486', 'Energy Economics and Policy', 3.0),
  ('ECO', 'ECO487', 'Applied Econometrics', 3.0),
  ('ECO', 'ECO489', 'Forecasting Methods in Business and Economics', 3.0),
  ('ECO', 'ECO491', 'Welfare Economics', 3.0),
  ('ECO', 'ECO492', 'Law and Economics', 3.0),
  ('ETE', 'ETE103', 'Structured Programming', 4.0),
  ('ETE', 'ETE107', 'Electrical Circuits - I', 4.0),
  ('ETE', 'ETE110', 'Electrical Circuits - II', 4.0),
  ('ETE', 'ETE212', 'Electronic Circuits - I', 4.0),
  ('ETE', 'ETE214', 'Electronic Circuits - II', 4.0),
  ('ETE', 'ETE216', 'Signals & Systems', 3.0),
  ('ETE', 'ETE217', 'Digital Electronics', 4.0),
  ('ETE', 'ETE223', 'Data Structure & Algorithm', 4.0),
  ('ETE', 'ETE302', 'Computer Communications & Networks', 4.0),
  ('ETE', 'ETE310', 'Electromagnetic Theory', 3.0),
  ('ETE', 'ETE312', 'Communication Theory', 3.0),
  ('ETE', 'ETE313', 'Microprocessors & Interfacing', 4.0),
  ('ETE', 'ETE314', 'Digital Communications', 4.0),
  ('ETE', 'ETE319', 'Electronic Properties of Materials', 3.0),
  ('ETE', 'ETE322', 'Digital Signal Processing', 4.0),
  ('ETE', 'ETE325', 'Control Systems', 4.0),
  ('ETE', 'ETE370', 'Applied Numerical Methods', 3.0),
  ('ETE', 'ETE417', 'Electrical Drives and Power Electronics', 3.0),
  ('ETE', 'ETE439', 'Engineering Ethics', 3.0),
  ('ETE', 'ETE441', 'Wireless & Mobile Communications', 3.0),
  ('ETE', 'ETE473', 'Project Management, Entrepreneurship and Industry Interaction', 3.0),
  ('ETE', 'ETE496', 'Capstone Project', 6.0),
  ('ETE', 'ETE400', 'Semiconductor Devices', 3.0),
  ('ETE', 'ETE401', 'VLSI Circuit Design', 4.0),
  ('ETE', 'ETE403', 'Optoelectronics', 3.0),
  ('ETE', 'ETE409', 'Semiconductor Processing & Fabrication', 3.0),
  ('ETE', 'ETE411', 'Analog Integrated Circuits', 3.0),
  ('ETE', 'ETE413', 'Introduction to Nanotechnology', 3.0),
  ('ETE', 'ETE419', 'Biomedical Electronics', 3.0),
  ('ETE', 'ETE422', 'Renewable Energy Technology', 3.0),
  ('ETE', 'ETE434', 'Microwave Engineering', 4.0),
  ('ETE', 'ETE442', 'Optical Fiber Communications', 4.0),
  ('ETE', 'ETE446', 'Satellite Communication', 3.0),
  ('ETE', 'ETE448', 'Information Theory & Coding', 3.0),
  ('ETE', 'ETE452', 'Multimedia Communications', 3.0),
  ('ETE', 'ETE418', 'Introduction to Embedded Systems', 3.0),
  ('ETE', 'ETE453', 'Computer and Cyber Security', 3.0),
  ('ETE', 'ETE461', 'Object Oriented Programming', 4.0),
  ('ETE', 'ETE462', 'Database Systems', 4.0),
  ('ETE', 'ETE466', 'Operating Systems', 3.0),
  ('ETE', 'ETE469', 'Computer Architecture', 3.0),
  ('ETE', 'ETE472', 'Speech & Image Processing', 4.0),
  ('ETE', 'ETE476', 'Artificial Intelligence', 3.0),
  ('ETE', 'ETE478', 'Machine Learning', 3.0),
  ('ETE', 'ETE479', 'Robotic Engineering', 3.0),
  ('ETE', 'ETE101', 'Introduction to Telecommunication Engineering', 3.0),
  ('GEB', 'GEB101', 'Basic Biology', 3.0),
  ('GEB', 'GEB103', 'Cell Biology-I', 3.0),
  ('GEB', 'GEB104', 'Basic Microbiology', 4.0),
  ('GEB', 'GEB105', 'Cell Biology-II', 3.0),
  ('GEB', 'GEB201', 'Basic Biochemistry', 4.0),
  ('GEB', 'GEB202', 'Molecular Biology', 4.0),
  ('GEB', 'GEB203', 'Animal Physiology', 3.0),
  ('GEB', 'GEB204', 'General Genetics and Genetic Analysis', 4.0),
  ('GEB', 'GEB301', 'Plant Physiology', 3.0),
  ('GEB', 'GEB302', 'Fundamentals of Genetic Engineering & Biotechnology', 3.0),
  ('GEB', 'GEB304', 'Immunology', 4.0),
  ('GEB', 'GEB305', 'General Virology', 3.0),
  ('GEB', 'GEB308', 'Separation Technologies and Analytical Methods', 4.0),
  ('GEB', 'GEB410', 'Current Topics in Genetic Engineering and Biotechnology', 3.0),
  ('GEB', 'GEB402', 'Advances in Recombinant Gene Technology', 4.0),
  ('GEB', 'GEB403', 'Animal and Plant Tissue Culture', 4.0),
  ('GEB', 'GEB406', 'Genomics, Proteomics and Bioinformatics', 3.0),
  ('GEB', 'GEB407', 'Industrial Biotechnology of Microbial Systems', 3.0),
  ('GEB', 'GEB420', 'Biochemistry & Molecular Biology of Diseases', 3.0),
  ('GEB', 'GEB490', 'Research Proposal', 3.0),
  ('GEB', 'GEB306', 'Environmental Biology', 3.0),
  ('GEB', 'GEB408', 'GMOs, Biosafety Regulations and Environmental Management', 3.0),
  ('GEB', 'GEB421', 'Methods in Enzymology', 3.0),
  ('GEB', 'GEB422', 'Developmental Biology', 3.0),
  ('GEB', 'GEB423', 'Human Molecular Genetics and Molecular Diagnostics', 3.0),
  ('GEB', 'GEB424', 'Microbial Genetics', 3.0),
  ('GEB', 'GEB425', 'Plant Development Biotechnology', 3.0),
  ('GEB', 'GEB426', 'Pharmaceutical Biotechnology', 3.0),
  ('GEB', 'GEB427', 'Stem Cells and Tissue Engineering', 3.0),
  ('GEB', 'GEB428', 'Forensic Biology', 3.0),
  ('GEB', 'GEB489', 'Industrial Training / Internship', 3.0),
  ('GEB', 'GEB499', 'Research Project', 3.0),
  ('GENED', 'GEN226', 'Emergence of Bangladesh', 3.0),
  ('GENED', 'GEN204', 'Western Thought', 3.0),
  ('GENED', 'GEN205', 'Introduction to Psychology', 3.0),
  ('GENED', 'GEN201', 'Bangladesh Studies', 3.0),
  ('GENED', 'GEN207', 'Industrial Psychology', 3.0),
  ('GENED', 'GEN208', 'Introduction to Philosophy', 3.0),
  ('GENED', 'GEN209', 'Introduction to Social Psychology', 3.0),
  ('GENED', 'GEN210', 'International Relations', 3.0),
  ('GENED', 'GEN211', 'Concept of Journalism and Media', 3.0),
  ('GENED', 'GEN212', 'Women in Development', 3.0),
  ('GENED', 'GEN213', 'Introduction to German Language', 3.0),
  ('GENED', 'GEN215', 'Introduction to French Language', 3.0),
  ('GENED', 'GEN216', 'Introduction to Spanish Language', 3.0),
  ('GENED', 'GEN217', 'Introduction to Chinese Language', 3.0),
  ('GENED', 'GEN218', 'Introduction to Arabic Language', 3.0),
  ('GENED', 'GEN220', 'Principles of Public Relations', 3.0),
  ('GENED', 'GEN221', 'Globalization, Development and Change', 3.0),
  ('GENED', 'GEN223', 'Contemporary Security Studies in Asia-Pacific', 3.0),
  ('GENED', 'GEN224', 'Bangla Language', 3.0),
  ('GENED', 'GEN239', 'Professional Ethics', 3.0),
  ('GENED', 'POP201', 'Health Challenges of Adolescents and Youths', 3.0),
  ('GENED', 'POP202', 'Introduction to Public Health', 3.0),
  ('GENED', 'POP203', 'Introduction to Population Studies', 3.0),
  ('GENED', 'GEN202', 'Eastern Culture and Heritage', 3.0),
  ('GENED', 'GEN203', 'Ecological System and Environment', 3.0),
  ('GENED', 'GEN214', 'Introduction to Development Studies', 3.0),
  ('GENED', 'GEN206', 'Introduction to Sociology', 3.0),
  ('ICE', 'ICE103', 'Structured Programming', 4.0),
  ('ICE', 'ICE107', 'Object Oriented Programming', 4.0),
  ('ICE', 'ICE109', 'Electrical Circuits', 4.0),
  ('ICE', 'ICE204', 'Discrete Mathematics', 3.0),
  ('ICE', 'ICE207', 'Data Structures', 4.0),
  ('ICE', 'ICE213', 'Electronic Circuits', 4.0),
  ('ICE', 'ICE216', 'Signals & Systems', 3.0),
  ('ICE', 'ICE217', 'Digital Electronics', 4.0),
  ('ICE', 'ICE245', 'Algorithms', 4.0),
  ('ICE', 'ICE275', 'Operating Systems', 3.0),
  ('ICE', 'ICE302', 'Computer Communications & Networks', 4.0),
  ('ICE', 'ICE305', 'Database Systems', 4.0),
  ('ICE', 'ICE310', 'Electromagnetic Theory', 3.0),
  ('ICE', 'ICE312', 'Communication Theory', 3.0),
  ('ICE', 'ICE313', 'Microprocessors & Interfacing', 4.0),
  ('ICE', 'ICE314', 'Digital Communications', 4.0),
  ('ICE', 'ICE322', 'Digital Signal Processing', 4.0),
  ('ICE', 'ICE370', 'Applied Numerical Methods', 3.0),
  ('ICE', 'ICE439', 'Engineering Ethics', 3.0),
  ('ICE', 'ICE441', 'Wireless & Mobile Communications', 3.0),
  ('ICE', 'ICE473', 'Project Management, Entrepreneurship and Industry Interaction', 3.0),
  ('ICE', 'ICE496', 'Capstone Project', 6.0),
  ('ICE', 'ICE453', 'Computer and Cyber Security', 3.0),
  ('ICE', 'ICE469', 'Computer Architecture', 3.0),
  ('ICE', 'ICE471', 'Network Programming', 4.0),
  ('ICE', 'ICE472', 'Speech & Image Processing', 4.0),
  ('ICE', 'ICE474', 'Computer Graphics & Visualizations', 3.0),
  ('ICE', 'ICE476', 'Artificial Intelligence', 3.0),
  ('ICE', 'ICE478', 'Machine Learning', 3.0),
  ('ICE', 'ICE479', 'Robotic Engineering', 3.0),
  ('ICE', 'ICE483', 'Data Science', 3.0),
  ('ICE', 'ICE484', 'Cyber Ethics and Legal Framework', 3.0),
  ('ICE', 'ICE485', 'Internet of Things', 3.0),
  ('ICE', 'ICE401', 'VLSI Circuit Design', 4.0),
  ('ICE', 'ICE434', 'Microwave Engineering', 4.0),
  ('ICE', 'ICE442', 'Optical Fiber Communications', 4.0),
  ('ICE', 'ICE446', 'Satellite Communications', 4.0),
  ('ICE', 'ICE448', 'Information Theory and Coding', 3.0),
  ('ICE', 'ICE452', 'Multimedia Communications', 3.0),
  ('ISLM', 'ISL101', 'Introduction to Information Studies and Library Management', 3.0),
  ('ISLM', 'ISL102', 'Organization of Information', 3.0),
  ('ISLM', 'ISL103', 'Information and Society', 3.0),
  ('ISLM', 'ISL104', 'New Technologies and Current Trends in Information Science', 3.0),
  ('ISLM', 'ISL201', 'Information Resources Development', 3.0),
  ('ISLM', 'ISL202', 'Information Users and their Needs', 3.0),
  ('ISLM', 'ISL203', 'Management of Information Institutions', 3.0),
  ('ISLM', 'ISL204', 'Information Sources and Services', 3.0),
  ('ISLM', 'ISL205', 'Writing, Editing and Publishing', 3.0),
  ('ISLM', 'ISL206', 'Bibliography, Reference and Citation', 3.0),
  ('ISLM', 'ISL207', 'Indexing and Abstracting', 3.0),
  ('ISLM', 'ISL208', 'Automation of Information Institutions', 3.0),
  ('ISLM', 'ISL301', 'Records and Archives Management', 3.0),
  ('ISLM', 'ISL302', 'Information Production, Marketing and Public Relation', 3.0),
  ('ISLM', 'ISL303', 'Documentation and Communication', 3.0),
  ('ISLM', 'ISL304', 'Research Methodology', 3.0),
  ('ISLM', 'ISL305', 'Organization of Knowledge (Classification Theory)', 3.0),
  ('ISLM', 'ISL306', 'Organization of Knowledge (Cataloguing Theory)', 3.0),
  ('ISLM', 'ISL307', 'Comparative Study of Information Systems', 3.0),
  ('ISLM', 'ISL308', 'Information Architecture', 3.0),
  ('ISLM', 'ISL309', 'Organization of Knowledge (Classification Practical)', 4.0),
  ('ISLM', 'ISL310', 'Organization of Knowledge (Cataloguing Practical)', 4.0),
  ('ISLM', 'ISL311', 'Applied Statistics', 3.0),
  ('ISLM', 'ISL401', 'Information Networking and Resource Sharing', 3.0),
  ('ISLM', 'ISL402', 'Analysis and Design of Information Systems', 3.0),
  ('ISLM', 'ISL403', 'Information Literacy', 3.0),
  ('ISLM', 'ISL409', 'Integrated Library System Development', 4.0),
  ('ISLM', 'ISL404', 'Computer Hardware Maintenance and Troubleshooting', 4.0),
  ('ISLM', 'ISL405', 'Server Administration', 4.0),
  ('ISLM', 'ISL406', 'Content Management System', 4.0),
  ('ISLM', 'ISL407', 'Database Design and Applications in Library and Information Systems', 4.0),
  ('ISLM', 'ISL408', 'Web Technologies and Web-based Information Services', 4.0),
  ('ISLM', 'ISL498', 'Project / Research Monograph', 3.0),
  ('ISLM', 'ISL499', 'Internship in Information Institutions', 3.0),
  ('LAW', 'LAW101', 'Law of Contract I', 3.0),
  ('LAW', 'LAW102', 'Muslim Law I', 3.0),
  ('LAW', 'LAW103', 'Law of Contract II', 3.0),
  ('LAW', 'LAW104', 'Muslim Law II', 3.0),
  ('LAW', 'LAW105', 'Interpretation of Statutes and English for Law', 3.0),
  ('LAW', 'LAW106', 'Constitutional Law I', 3.0),
  ('LAW', 'LAW107', 'Legal System of Bangladesh', 3.0),
  ('LAW', 'LAW108', 'Administrative Law', 3.0),
  ('LAW', 'LAW201', 'Constitutional Law II', 3.0),
  ('LAW', 'LAW202', 'Criminal Law I', 3.0),
  ('LAW', 'LAW203', 'Hindu Law', 3.0),
  ('LAW', 'LAW204', 'Criminal Law II', 3.0),
  ('LAW', 'LAW205', 'Law of Tort', 3.0),
  ('LAW', 'LAW206', 'Land Law', 3.0),
  ('LAW', 'LAW207', 'Criminology', 3.0),
  ('LAW', 'LAW208', 'Laws on Partnership, Sale and Carriage of Goods', 3.0),
  ('LAW', 'LAW209', 'Laws on Equity and Trust', 3.0),
  ('LAW', 'LAW301', 'Laws on Taxation', 3.0),
  ('LAW', 'LAW302', 'Jurisprudence', 3.0),
  ('LAW', 'LAW303', 'Laws on Transfer of Property and Registration', 3.0),
  ('LAW', 'LAW304', 'Labour Law', 3.0),
  ('LAW', 'LAW305', 'Law of Evidence I', 3.0),
  ('LAW', 'LAW306', 'Law on Insurance & Negotiable Instrument', 3.0),
  ('LAW', 'LAW307', 'Laws on Specific Relief and Limitation', 3.0),
  ('LAW', 'LAW308', 'Company Law', 3.0),
  ('LAW', 'LAW309', 'Law of Evidence II', 3.0),
  ('LAW', 'LAW310', 'Law on Criminal Procedure I', 3.0),
  ('LAW', 'LAW311', 'Law on Civil Procedure I', 3.0),
  ('LAW', 'LAW312', 'International Law I', 3.0),
  ('LAW', 'LAW401', 'Law on Criminal Procedure II', 3.0),
  ('LAW', 'LAW402', 'Law on Civil Procedure II', 3.0),
  ('LAW', 'LAW403', 'International Law II', 3.0),
  ('LAW', 'LAW404', 'Legal Drafting I (Criminal)', 3.0),
  ('LAW', 'LAW405', 'Legal Drafting II (Civil)', 3.0),
  ('LAW', 'LAW406', 'Supervised Dissertation', 3.0),
  ('LAW', 'LAW407', 'Legal Drafting III (Civil)', 3.0),
  ('LAW', 'LAW408', 'Trial and Advocacy Training (Criminal)', 3.0),
  ('LAW', 'LAW409', 'Trial and Advocacy Training (Civil)', 3.0),
  ('MBS', 'MAT110', 'Mathematics for Business and Economics I', 3.0),
  ('MBS', 'MAT100', 'College Mathematics (Compulsory for those who have no mathematics in HSC or equivalent level)', 3.0),
  ('MBS', 'MAT211', 'Mathematics for Business and Economics II', 3.0),
  ('MBS', 'MAT101', 'Differential & Integral Calculus', 3.0),
  ('MBS', 'MAT102', 'Differential Equations & Special Functions', 3.0),
  ('MBS', 'MAT206', 'Basic Algebra and Linear Algebra', 3.0),
  ('MBS', 'PHY109', 'Engineering Physics-I (Introductory Classical Physics)', 4.0),
  ('MBS', 'PHY209', 'Engineering Physics-II (Introductory Quantum Physics)', 3.0),
  ('MBS', 'CHE109', 'Engineering Chemistry', 4.0),
  ('MBS', 'MAT104', 'Coordinate Geometry and Vector Analysis', 3.0),
  ('MBS', 'MAT205', 'Linear Algebra and Complex Variable', 3.0),
  ('MBS', 'STA102', 'Statistics and Probability', 3.0),
  ('MBS', 'CHE101', 'Introduction to Chemistry', 4.0),
  ('MBS', 'STA208', 'Statistics for Biologists', 3.0),
  ('MBS', 'CHE108', 'Chemistry for Biologists - I', 4.0),
  ('MBS', 'CHE208', 'Chemistry for Biologists - II', 4.0),
  ('MBS', 'PHY108', 'Physics for Biologists - I', 4.0),
  ('MBS', 'PHY208', 'Physics for Biologists - II', 4.0),
  ('MBS', 'PHY100', 'Introductory Physics', 3.0),
  ('MBS', 'MAT201', 'Linear Algebra', 3.0),
  ('MBS', 'MAT407', 'Advanced Calculus', 3.0),
  ('MBS', 'MAT470', 'Real Analysis', 3.0),
  ('MBS', 'STA427', 'Mathematical Statistics', 3.0),
  ('PHRM', 'PHRM101', 'Physical Pharmacy I', 4.0),
  ('PHRM', 'PHRM102', 'Cell Biology and Anatomy', 3.0),
  ('PHRM', 'PHRM103', 'Organic Pharmacy I', 4.0),
  ('PHRM', 'PHRM201', 'Human Physiology I', 4.0),
  ('PHRM', 'PHRM202', 'Basic Microbiology', 4.0),
  ('PHRM', 'PHRM203', 'Pharmaceutical Analysis I', 4.0),
  ('PHRM', 'PHRM204', 'Physical Pharmacy II', 4.0),
  ('PHRM', 'PHRM205', 'Inorganic Pharmacy', 4.0),
  ('PHRM', 'PHRM206', 'Biochemistry', 4.0),
  ('PHRM', 'PHRM207', 'Pharmacognosy I', 4.0),
  ('PHRM', 'PHRM208', 'Human Physiology II', 4.0),
  ('PHRM', 'PHRM209', 'Statistics for Pharmaceutical Sciences', 3.0),
  ('PHRM', 'PHRM210', 'Pharmaceutics I', 4.0),
  ('PHRM', 'PHRM211', 'Organic Pharmacy II', 3.0),
  ('PHRM', 'PHRM301', 'Pharmacology I', 3.0),
  ('PHRM', 'PHRM302', 'Medicinal Chemistry I', 3.0),
  ('PHRM', 'PHRM303', 'Pharmacognosy II', 3.0),
  ('PHRM', 'PHRM304', 'Medicinal Chemistry II', 4.0),
  ('PHRM', 'PHRM305', 'Pharmaceutical Microbiology', 4.0),
  ('PHRM', 'PHRM306', 'Pharmacology II', 4.0),
  ('PHRM', 'PHRM307', 'Pharmaceutical Technology I', 3.0),
  ('PHRM', 'PHRM308', 'Pharmaceutics II', 4.0),
  ('PHRM', 'PHRM309', 'Pharmaceutical Analysis II', 4.0),
  ('PHRM', 'PHRM310', 'Toxicology', 3.0),
  ('PHRM', 'PHRM311', 'Clinical & Hospital Pharmacy', 3.0),
  ('PHRM', 'PHRM312', 'Pharmaceutical Analysis III', 3.0),
  ('PHRM', 'PHRM401', 'Pharmaceutical Management & Marketing', 3.0),
  ('PHRM', 'PHRM402', 'Pharmaceutical Technology II', 4.0),
  ('PHRM', 'PHRM403', 'Drug Design and Development', 3.0),
  ('PHRM', 'PHRM404', 'Pharmaceutical Research', 5.0),
  ('PHRM', 'PHRM405', 'Pharmacy Quality Assurance', 3.0),
  ('PHRM', 'PHRM406', 'Biopharmaceutics & Pharmacokinetics', 4.0),
  ('PHRM', 'PHRM407', 'Pharmaceutical Biotechnology', 3.0),
  ('PHRM', 'PHRM409', 'Advanced Pharmaceutical Analysis', 4.0),
  ('PHRM', 'PHRM410', 'Pharmacy Law and Ethics', 3.0),
  ('PHRM', 'PHRM411', 'Cosmetology', 4.0),
  ('PHRM', 'PHRM412', 'Medicinal Chemistry III', 3.0),
  ('PHRM', 'PHRM413', 'Pharmacology III', 4.0),
  ('PHRM', 'PHRM414', 'Pharmaceutical Engineering', 3.0),
  ('SOC', 'SOC101', 'Introduction to Sociology', 3.0),
  ('SOC', 'SOC102', 'Introduction to Anthropology', 3.0),
  ('SOC', 'SOC202', 'Social Psychology', 3.0),
  ('SOC', 'SOC211', 'Eastern Culture & Heritage', 3.0),
  ('SOC', 'SOC212', 'Social Ecology, Environment & Society', 3.0),
  ('SOC', 'SOC213', 'Women in Development', 3.0),
  ('SOC', 'SOC214', 'Introduction to Development Studies', 3.0),
  ('SOC', 'SOC215', 'Principles of Social & Public Relations', 3.0),
  ('SOC', 'SOC216', 'Globalization and Social Identity', 3.0),
  ('SOC', 'SOC217', 'Religion, Ethnicity, Culture and Development in South Asia', 3.0),
  ('SOC', 'SOC209', 'Industrial Sociology', 3.0),
  ('SOC', 'SOC310', 'Sociology of Organization', 3.0),
  ('SOC', 'SOC106', 'Historical Sociology', 3.0),
  ('SOC', 'SOC107', 'Social Problem and Analysis', 3.0),
  ('SOC', 'SOC201', 'Sociology of Family and Marriage', 3.0),
  ('SOC', 'SOC205', 'Rural Sociology', 3.0),
  ('SOC', 'SOC206', 'Statistics for Sociology', 3.0),
  ('SOC', 'SOC210', 'Community, Communication, and Culture', 3.0),
  ('SOC', 'SOC218', 'Sociology of Gender', 3.0),
  ('SOC', 'SOC220', 'Quantitative Research Methodology', 3.0),
  ('SOC', 'SOC301', 'Qualitative Research Methodology', 3.0),
  ('SOC', 'SOC302', 'Social Structure of Bangladesh', 3.0),
  ('SOC', 'SOC303', 'Urban Sociology', 3.0),
  ('SOC', 'SOC304', 'Sociology of Environment', 3.0),
  ('SOC', 'SOC305', 'Medical Sociology', 3.0),
  ('SOC', 'SOC306', 'Social Problem Analysis', 3.0),
  ('SOC', 'SOC309', 'Sociology of Education', 3.0),
  ('SOC', 'SOC312', 'Social Demography', 3.0),
  ('SOC', 'SOC319', 'Early Social Thought', 3.0),
  ('SOC', 'SOC401', 'Classical Sociological Theories', 3.0),
  ('SOC', 'SOC406', 'Sociology of Development', 3.0),
  ('SOC', 'SOC407', 'Contemporary Sociological Theories', 3.0),
  ('SOC', 'SOC105', 'Peasant Societies', 3.0),
  ('SOC', 'SOC203', 'Social Group and Social Development', 3.0),
  ('SOC', 'SOC208', 'Sociology of Social Stratification and Inequality', 3.0),
  ('SOC', 'SOC219', 'Sociology of Race and Ethnicity', 3.0),
  ('SOC', 'SOC221', 'Social History and World Civilization', 3.0),
  ('SOC', 'SOC307', 'Bangladesh Society and Culture', 3.0),
  ('SOC', 'SOC308', 'Social Services in Bangladesh', 3.0),
  ('SOC', 'SOC311', 'Feminist Thought', 3.0),
  ('SOC', 'SOC313', 'Criminology', 3.0),
  ('SOC', 'SOC314', 'Sociology of Aging', 3.0),
  ('SOC', 'SOC315', 'Principles of Economic Sociology', 3.0),
  ('SOC', 'SOC316', 'Globalization, Migration, Development and Refugee Issues', 3.0),
  ('SOC', 'SOC317', 'Sociology of Science and Technology', 3.0),
  ('SOC', 'SOC318', 'Sociology of Religion', 3.0),
  ('SOC', 'SOC320', 'Social Gerontology', 3.0),
  ('SOC', 'SOC402', 'Sociology of Poverty', 3.0),
  ('SOC', 'SOC403', 'Political Sociology', 3.0),
  ('SOC', 'SOC404', 'Marxist Sociology', 3.0),
  ('SOC', 'SOC405', 'Social Forestry', 3.0),
  ('SOC', 'SOC408', 'Sociology of Gender Planning and Development', 3.0),
  ('SOC', 'SOC409', 'Sociology of Mass Communication', 3.0),
  ('SOC', 'SOC410', 'Community Development Organizations and Social Change', 3.0),
  ('SOC', 'SOC411', 'Human Rights and Social Justice', 3.0),
  ('SOC', 'SOC412', 'Social Intervention and Practices', 3.0),
  ('SOC', 'SOC415', 'Women, Society and Development', 3.0),
  ('SOC', 'SOC416', 'Social Changes in Bangladesh', 3.0),
  ('SOC', 'SOC413', 'Research Project / Monograph', 6.0),
  ('SOC', 'SOC414', 'Practicum and Internship', 6.0)
) as c(dept_short, code, name, credit)
where d.short_name = c.dept_short
-- Conservative: never overwrite an existing course row (avoids silently renaming
-- a course code that a file/purchase may already reference). See chat notes on
-- CSE303 / CSE327 / CSE423 mismatches against the old placeholder seed.
on conflict (department_id, course_code) do nothing;
